services:
  api:
    build:
      target: backend
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  web:
    build:
      target: frontend
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:80
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
