name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_REGISTRY_URL: ghcr.io
  DOCKER_NAMESPACE: ${{ github.repository_owner }}
  DOCKER_IMAGE_NAME: monorepo
  HUSKY: 0

jobs:
  setup-pnpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

  install-dependencies:
    runs-on: ubuntu-latest
    needs: setup-pnpm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          pnpm install --frozen-lockfile

  check-types:
    runs-on: ubuntu-latest
    needs:
      - install-dependencies
      - setup-pnpm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load Cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile --offline

      - name: Build
        run: |
          pnpm --filter=common build

      - name: Check Types
        run: |
          pnpm run typecheck

  lint:
    runs-on: ubuntu-latest
    needs:
        - install-dependencies
        - setup-pnpm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load Cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Lint
        run: |
          pnpm run lint

  test:
    runs-on: ubuntu-latest
    needs:
        - install-dependencies
        - setup-pnpm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load Cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile --offline

      - name: Build
        run: |
          pnpm --filter=common build

      - name: Run Tests
        run: |
          pnpm run test

  build-frontend:
    runs-on: ubuntu-latest
    environment: build
    needs:
      - lint
      - test
      - check-types
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build
          --target frontend
          --tag $DOCKER_REGISTRY_URL/$DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME-frontend:latest
          .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.DOCKER_REGISTRY_URL}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push the latest tag
        run: docker push $DOCKER_REGISTRY_URL/$DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME-frontend:latest

  build-backend:
    runs-on: ubuntu-latest
    environment: build
    needs:
      - lint
      - test
      - check-types
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build
          --target backend
          --tag $DOCKER_REGISTRY_URL/$DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME-backend:latest
          .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.DOCKER_REGISTRY_URL}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push the latest tag
        run: docker push $DOCKER_REGISTRY_URL/$DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME-backend:latest
